server:
  port: 10001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_vip?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhxbb20010821
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 43.142.73.143
    port: 6379
    password: zhxbb20010821
    database: 0

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto